[project]
name = "tercera-pre-entrega-lourdes-ramirez"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-widget-tweaks>=1.5.0",
    "django>=5.1.4",
    "pillow>=11.0.0",
]
