# Generated by Django 5.1.4 on 2024-12-16 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('proteína', 'Proteína'), ('carbohidrato', 'Carbohidrato'), ('grasa', 'Grasa'), ('vegetal', 'Vegetal')], max_length=50)),
                ('kcal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_diaria_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_consumo', models.DateField()),
                ('alimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.alimento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.usuario')),
            ],
        ),
    ]
