# Generated by Django 5.1.4 on 2024-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_categoria_alter_alimento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil'),
        ),
    ]
