# Generated by Django 5.1.4 on 2024-12-28 20:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_usuario_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='consumo',
            options={'ordering': ('-fecha_consumo',)},
        ),
        migrations.AddField(
            model_name='consumo',
            name='kcal_total',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.alimento'),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_consumo',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='alimento',
            unique_together={('tipo', 'nombre')},
        ),
    ]
