# Generated by Django 5.1.4 on 2024-12-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_alimento_options_alter_consumo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.usuario', verbose_name='paciente'),
        ),
    ]
