# Generated by Django 5.1.4 on 2024-12-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_consumo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='kcal_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
