# Generated by Django 5.1.4 on 2024-12-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_alter_consumo_kcal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='kcal_total',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
