# Generated by Django 5.1.4 on 2024-12-29 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_consumo_kcal_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='fecha_consumo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
